### ISSUE TITLE
NHibernate.spatial     IGeometry    get

### ISSUE THREAD

**Issue by rightthgir** [stoveproject/Stove#155]

**Comment by rightthgir** [comment]
using System.Reflection;
using System.Web.Http;
using System.Web.Http.Cors;

using Autofac.Extras.IocManager;
using Autofac.Integration.WebApi;
using HibernatingRhinos.Profiler.Appender.NHibernate;
using Microsoft.Owin;

using Owin;


using FluentNHibernate.Cfg;
using FluentNHibernate.Cfg.Db;

using NHibernate.Spatial.Dialect;
using NHibernate.Tool.hbm2ddl;
//using Stove.Dapper;
//using Stove.Demo.ConsoleApp.Nh.Mappings.Nh;
using Stove.Demo.ConsoleApp.Nh.SessionContexts;
using Stove.Demo.ConsoleApp.Nh.Transactioning;
using Stove.NHibernate;
using Swashbuckle.Application;
using Stove.Demo.ConsoleApp.Nh;
using Stove.Demo.ConsoleApp.Nh.Entities;
using FluentNHibernate.Automapping;
using Stove.Demo.ConsoleApp.Nh.Mappings.Nh;

[assembly: OwinStartup(typeof(Startup))]

namespace Stove.Demo.ConsoleApp.Nh
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var config = new HttpConfiguration();
            NHibernateProfiler.Initialize();

            IRootResolver rootResolver = IocBuilder
                                                   .New
                                                   .UseAutofacContainerBuilder()
                                                   .UseStoveWithNullables<StoveDemoBootstrapper>(true)
                                                   .UseStoveNHibernate(nhCfg =>
                                                    {
                                                        nhCfg.AddFluentConfigurationFor<PrimarySessionContext>(() =>
                                                        {
                                                            return Fluently.Configure()
                                                                        .Database(MsSqlConfiguration.MsSql2012.ConnectionString(nhCfg.Configuration.DefaultNameOrConnectionString).ShowSql().Dialect(typeof(MsSql2012GeometryDialect).AssemblyQualifiedName))
          //.Mappings(m => m.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
                                                                   .Mappings(m => m.FluentMappings.AddFromAssemblyOf<ProductMap>().Conventions.Add(new EnumConvention(), new MsSqlGeometryConvention()))
                                                                        //.Mappings(x => x.AutoMappings.Add(
                                                                        //                AutoMap.AssemblyOf<Product>(new AutomappingConfiguration()).Conventions.Add(new MsSqlGeometryConvention()).UseOverridesFromAssemblyOf<ProductOverrides>()))
                                                                        .ExposeConfiguration(config2 => new SchemaUpdate(config2).Execute(false, true));
                                                        });

                                                        

//                                                        nhCfg.AddFluentConfigurationFor<SecondarySessionContext>(() =>
//                                                        {
//                                                            return Fluently.Configure()
//                                                                .Database(MsSqlConfiguration.MsSql2012.ConnectionString(nhCfg.Configuration.TypedConnectionStrings[typeof(SecondarySessionContext)]).ShowSql().Dialect(typeof(MsSql2012GeometryDialect).AssemblyQualifiedName))
//                                                                                                                                 //.Mappings(m => m.FluentMappings.AddFromAssembly(Assembly.GetExecutingAssembly()))
//                                                                                                                                 .Mappings(x => x.AutoMappings.Add(
//                                                              AutoMap.AssemblyOf<Product>(new AutomappingConfiguration()).Conventions.Add(new EnumConvention(), new MsSqlGeometryConvention()).UseOverridesFromAssemblyOf<ProductOverrides>()))
//.ExposeConfiguration(config2 => new SchemaUpdate(config2).Execute(false, true));
//                                                        });

                                                        return nhCfg;
                                                    })
                                                   .UseStoveNullLogger()
                                                   //.UseStoveDapper()
                                                   .UseStoveEventBus()
                                                   .RegisterServices(r =>
                                                   {
                                                       r.RegisterAssemblyByConvention(Assembly.GetExecutingAssembly());
                                                       r.UseBuilder(cb =>
                                                       {
                                                           cb.RegisterApiControllers(Assembly.GetExecutingAssembly());
                                                           cb.RegisterWebApiFilterProvider(config);
                                                       });
                                                   })
                                                   .CreateResolver();

            config.DependencyResolver = new AutofacWebApiDependencyResolver(rootResolver.Container);
            config.EnableSwagger("docs/{apiVersion}/swagger", c => { c.SingleApiVersion("v1", "Stove WebApi").Description("Stove WebApi documentation."); })
                  .EnableSwaggerUi("help/{*assetPath}", c => { c.DisableValidator(); });

            config.MapHttpAttributeRoutes();
            config.EnableCors(new EnableCorsAttribute("*", "*", "*"));
            config.Routes.MapHttpRoute(
                "DefaultApi",
                "api/{controller}/{id}",
                new { id = RouteParameter.Optional }
            );

            app.UseWebApi(config);
        }
    }
}

**Comment by rightthgir** [comment]
using FluentNHibernate.Conventions;
using FluentNHibernate.Conventions.AcceptanceCriteria;
using FluentNHibernate.Conventions.Inspections;
using FluentNHibernate.Conventions.Instances;
using GeoAPI.Geometries;
using NHibernate.Spatial.Type;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stove.Demo.ConsoleApp.Nh.Transactioning
{
    public class MsSqlGeometryConvention : IUserTypeConvention
    {
        public void Accept(IAcceptanceCriteria<IPropertyInspector> criteria)
        {
            criteria.Expect(x => typeof(IGeometry).IsAssignableFrom(x.Property.PropertyType));
        }

        public void Apply(IPropertyInstance target)
        {
            target.CustomType(typeof(MsSql2008GeometryType));
            target.CustomSqlType("GEOMETRY");
        }
    }
}

**Comment by rightthgir** [comment]
using GeoAPI.Geometries;
using NetTopologySuite.Features;
using Stove.Domain.Entities;
using Stove.Domain.Entities.Auditing;
using System.ComponentModel.DataAnnotations.Schema;

namespace Stove.Demo.ConsoleApp.Nh.Entities
{
    public class Product : Entity
    {
        protected Product()
        {
        }

        //public Product(string name) : this()
        //{
        //    Name = name;
        //}
        public Product(string name,IGeometry geometry) : this()
        {
            Name = name;
            this.Shape = geometry;
        }

        public virtual IGeometry Shape { get; set; }


        public virtual string Name { get; set; }


        //[NotMapped]
        //public override bool IsSpatialClass
        //{
        //    get { return true; }
        //}

        //[NotMapped]
        //public override IFeature ToFeature
        //{
        //    get
        //    {
        //        AttributesTable attributes = new AttributesTable();
        //        attributes.AddAttribute("Id", Id);
        //        attributes.AddAttribute("Name", Name);

        //        IFeature feature = new Feature(Shape, attributes);
        //        return feature;
        //    }
        //}


    }
}

**Comment by rightthgir** [comment]
using GeoAPI.Geometries;
using NHibernate.Spatial.Type;
using Stove.Demo.ConsoleApp.Nh.Entities;
using Stove.NHibernate.EntityMappings;

namespace Stove.Demo.ConsoleApp.Nh.Mappings.Nh
{
    public class ProductMap : EntityMap<Product>
    {
        public ProductMap() : base("Products")
        {
            //this.MapFullAudited();
            ImportType<IGeometry>();
            Map(x => x.Name);
            Map(x => x.Shape).CustomType<MsSql2008GeometryType>();//.Not.Nullable();


        }
    }
}

**Comment by rightthgir** [comment]
using FluentNHibernate.Conventions;
using FluentNHibernate.Conventions.AcceptanceCriteria;
using FluentNHibernate.Conventions.Inspections;
using FluentNHibernate.Conventions.Instances;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stove.Demo.ConsoleApp.Nh.Transactioning
{
    public class EnumConvention : IUserTypeConvention
    {
        public void Accept(IAcceptanceCriteria<IPropertyInspector> criteria)
        {
            criteria.Expect(x => x.Property.PropertyType.IsEnum);
        }

        public void Apply(IPropertyInstance target)
        {
            target.CustomType(target.Property.PropertyType);
        }
    }
}

**Comment by rightthgir** [comment]
using NetTopologySuite.Geometries;
//using Stove.Dapper.Repositories;
using Stove.Demo.ConsoleApp.Nh.Entities;
using Stove.Domain.Repositories;
using Stove.Domain.Services;
using Stove.Domain.Uow;
using Stove.Runtime.Session;
using System.Collections.Generic;
using System.Transactions;

namespace Stove.Demo.ConsoleApp.Nh
{
    public class ProductDomainService : DomainService
    {
        //private readonly IDapperRepository<Category> _categoryDapperRepository;
        //private readonly IRepository<Category> _categoryRepository;
        //private readonly IDapperRepository<Product> _productDapperRepository;
        private readonly IRepository<Product> _productRepository;
        private readonly IUnitOfWorkManager _unitOfWorkManager;

        public ProductDomainService(
            //IDapperRepository<Product> productDapperRepository,
            IRepository<Product> productRepository,
            IUnitOfWorkManager unitOfWorkManager
            //IRepository<Category> categoryRepository/*,*/
            //IDapperRepository<Category> categoryDapperRepository
            )
        {
            //_productDapperRepository = productDapperRepository;
            _productRepository = productRepository;
            _unitOfWorkManager = unitOfWorkManager;
            //_categoryRepository = categoryRepository;
            //_categoryDapperRepository = categoryDapperRepository;
        }

        public IStoveSession StoveSession { get; set; }

        public void DoSomeCoolStuff()
        {
            //List<Product> ds2 = _productRepository.GetAllList();

            //using (StoveSession.Use(1))
            //{
            using (
                IUnitOfWorkCompleteHandle uow = _unitOfWorkManager.Begin())
            {
                //_productDapperRepository.Insert(new Product("JeanFromDapper"));

                //_categoryDapperRepository.Insert(new Category("Selam"));

                //Product product = _productRepository.FirstOrDefault(x => x.Name == "JeanFromDapper");

                _productRepository.Insert(new Product("JeanFromNH", new Point(1, 2)));

                //_productRepository.InsertAndGetId(new Product("JeanFromNH"));

                //_categoryRepository.Insert(new Category("Selam"));
                _unitOfWorkManager.Current.SaveChanges();

                List<Product> ds = _productRepository.GetAllList();

                uow.Complete();

                using (IUnitOfWorkCompleteHandle uow2 = _unitOfWorkManager.Begin())
                {
                    List<Product> ds2 = _productRepository.GetAllList();
                    uow2.Complete();
                }
            }
            //}
        }
    }
}

**Comment by rightthgir** [comment]
this is  the  question.

the "_productRepository.Insert(new Product("JeanFromNH", new Point(1, 2)));"   is sucess，    but  ， the 
 result  of  “List<Product> ds = _productRepository.GetAllList();”，    the  shape  is   null.

**Comment by rightthgir** [comment]
help  me,    please

**Comment by osoykan** [comment]
Hi @rightthgir,

It seems you've already solved the problem. But as an advise If I may, please read [this](https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612) guide before open an issue to any Github repository since it may sometimes be unintelligeble. 

I'm closing this one.
Cheers.
